#!/usr/bin/env python3

import re
import sys

crud = sys.stdin.readlines()
out = []

badhead = re.compile("^(\>*) On .* (AM|PM) (.* \<.*@.*\>) wrote:$")
for i in range(len(crud)):
    line = crud[i].replace("> >", ">>")

    m = badhead.search(line)
    if m:
        line = f"{m.group(1)} {m.group(3)} writes:\n"

    out.append(line)

print("".join(out))
print("\n")
